=== amberlinda15/cat-test-1/cat_test_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<emp:schema xmlns:emp = "http://www.w3.org/2001/XMLSchema">
	<emp:element name = "Company">
		<emp:complexType>
		<emp:sequence>
			<emp:element name="Employee" maxOccurs = "unbounded">
				<emp:complexType>
				<emp:sequence>
					<emp:element name="Emp-id" type="emp:string"></emp:element>
					<emp:element name="Emp-name" type="emp:string"></emp:element>
					<emp:element name="Emp-age" type="emp:integer"></emp:element>
					<emp:element name="Emp-salary" type="emp:integer">
						<emp:simpleType>
							<emp:restriction base="emp:integer">
								<emp:minInclusive value="50000"/>
								<emp:maxInclusive value="200000"/>
							</emp:restriction>
						</emp:simpleType>
					</emp:element>
					<emp:element name="Emp-emailid" type="emp:string"></emp:element>
					<emp:element name="Emp-Phonenum" type="emp:integer"></emp:element>
					<emp:element name="Emp-designation" type="emp:string"></emp:element>
				</emp:sequence>
				</emp:complexType>
			</emp:element>
		</emp:sequence>
		</emp:complexType>
		<emp:unique name="uniqueId">
			<emp:selector xpath="Employee"/>
			<emp:field xpath="Emp-id"/>
		</emp:unique>
	</emp:element>
</emp:schema>

=== amberlinda15/cat-test-1/cat_test_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cat_test_1.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="cat_test_1.xsd">
	<Employee >
		<Emp-id>1</Emp-id>
		<Emp-name>Aadarsh verma</Emp-name>
		<Emp-age>22</Emp-age>
		<Emp-salary>55000</Emp-salary>
		<Emp-emailid>aadarshverma@gmail.com</Emp-emailid>
		<Emp-Phonenum>9865742145</Emp-Phonenum>
		<Emp-designation>operations</Emp-designation>
	</Employee>
	<Employee >
		<Emp-id>2</Emp-id>
		<Emp-name>Ankur sharma</Emp-name>
		<Emp-age>50</Emp-age>
		<Emp-salary>65000</Emp-salary>
		<Emp-emailid>ankursharma@gmail.com</Emp-emailid>
		<Emp-Phonenum>8654782145</Emp-Phonenum>
		<Emp-designation>operations manager</Emp-designation>
	</Employee>
	<Employee >
		<Emp-id>3</Emp-id>
		<Emp-name>Abhishek rathi</Emp-name>
		<Emp-age>32</Emp-age>
		<Emp-salary>50000</Emp-salary>
		<Emp-emailid>abhishekrathi@gmail.com</Emp-emailid>
		<Emp-Phonenum>7256489562</Emp-Phonenum>
		<Emp-designation>finance</Emp-designation>
	</Employee>
	<Employee >
		<Emp-id>4</Emp-id>
		<Emp-name>madhumita k</Emp-name>
		<Emp-age>25</Emp-age>
		<Emp-salary>70000</Emp-salary>
		<Emp-emailid>madhumitak@gmail.com</Emp-emailid>
		<Emp-Phonenum>654782541</Emp-Phonenum>
		<Emp-designation>finance</Emp-designation>
	</Employee>
	<Employee >
		<Emp-id>5</Emp-id>
		<Emp-name>Pooja</Emp-name>
		<Emp-age>40</Emp-age>
		<Emp-salary>60000</Emp-salary>
		<Emp-emailid>Pooja@gmail.com</Emp-emailid>
		<Emp-Phonenum>241578625</Emp-Phonenum>
		<Emp-designation>marketing</Emp-designation>
	</Employee>
	<Employee >
		<Emp-id>6</Emp-id>
		<Emp-name>Rahul K</Emp-name>
		<Emp-age>60</Emp-age>
		<Emp-salary>100000</Emp-salary>
		<Emp-emailid>rahulK@gmail.com</Emp-emailid>
		<Emp-Phonenum>92541578563</Emp-Phonenum>
		<Emp-designation>finance manager</Emp-designation>
	</Employee>
	<Employee >
		<Emp-id>7</Emp-id>
		<Emp-name>Abhishek beck</Emp-name>
		<Emp-age>29</Emp-age>
		<Emp-salary>70000</Emp-salary>
		<Emp-emailid>abhishekbeck@gmail.com</Emp-emailid>
		<Emp-Phonenum>7584256982</Emp-Phonenum>
		<Emp-designation>operations manager</Emp-designation>
	</Employee>
</Company>
